name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "*/120 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics.user_details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Kolkata
          repositories_affiliations: ""
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage