name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "*/10 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Kolkata
          repositories_affiliations: ""
          base: header, activity, community, repositories, metadata
      - name: Metrics insights
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.insights.html
          token: ${{ secrets.METRICS_TOKEN }}
          config_output: insights
